include:
  - component: $CI_SERVER_FQDN/flarenetwork/infra-public/ci-components/dependency-track@~latest

variables:
  PATTERN_FULL: '^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-(?:(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?:[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
  PATTERN_SEMI: '^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$'
  AUTH_TOKEN: $NPM_AUTH_TOKEN
  NODE_VERSION: "24.13.0"

stages:
    - build
    - test
    - publish
    - sbom
   
build:
    stage: build
    image: node:$NODE_VERSION
    before_script:
        - corepack enable pnpm
        - pnpm install --frozen-lockfile
    script:
        - pnpm build

test:
    stage: test
    image: node:$NODE_VERSION
    before_script:
        - corepack enable pnpm
        - pnpm install --frozen-lockfile
    script:
        - pnpm test:all

lint:
  stage: test
  image: node:$NODE_VERSION
  before_script:
    - corepack enable pnpm
    - pnpm install --frozen-lockfile
  script:
    - pnpm lint:check
    - pnpm format:check

.check-tag_template:
  script:
    - result=$(grep -Pc "$PATTERN_FULL" <<< $CI_COMMIT_TAG) || true
    - if [ $result -eq 0 ]; then echo "Tag has wrong format"; exit 1; fi 

.compare-versions_template:
  script:
    - apt-get update
    - apt-get install jq -y
    - pver=$(echo "v$(jq -r .version package.json)")
    - if [ $pver != $CI_COMMIT_TAG ]; then echo "Tag and package.json versions do not match"; exit 1; fi;

.publish-npm_template:
  image: node:$NODE_VERSION
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - apt-get update
    - apt-get install -y gettext
    - result=$(grep -Pc "$PATTERN_SEMI" <<< "$CI_COMMIT_TAG") || true
    - corepack enable pnpm
    - pnpm install --frozen-lockfile
    - pnpm build
    - if [ $result -eq 1 ]; then pnpm publish --publish-branch main; else pnpm publish --tag beta --no-git-checks; fi;


check-tag:
  stage: publish
  extends: .check-tag_template
  rules:
    - if: '$CI_COMMIT_TAG'

compare-versions:
  stage: publish
  extends: .compare-versions_template
  needs:
    - job: check-tag
  rules:
    - if: '$CI_COMMIT_TAG'
  
publish-npm:
  stage: publish
  extends: .publish-npm_template
  needs:
    - job: compare-versions
  rules:
    - if: '$CI_COMMIT_TAG'